# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Biweight kernel function
NULL

biweight_kernel <- function(u) {
    .Call(`_adaptiveFTS_biweight_kernel`, u)
}

triweight_kernel <- function(u) {
    .Call(`_adaptiveFTS_triweight_kernel`, u)
}

tricube_kernel <- function(u) {
    .Call(`_adaptiveFTS_tricube_kernel`, u)
}

epanechnikov_kernel <- function(u) {
    .Call(`_adaptiveFTS_epanechnikov_kernel`, u)
}

triangular_kernel <- function(u) {
    .Call(`_adaptiveFTS_triangular_kernel`, u)
}

uniform_kernel <- function(u) {
    .Call(`_adaptiveFTS_uniform_kernel`, u)
}

estimate_nw_cpp <- function(y, t, tnew, h, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_nw_cpp`, y, t, tnew, h, kernel_name)
}

estimate_nw_bw_cpp <- function(y, t, bw_grid, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_nw_bw_cpp`, y, t, bw_grid, kernel_name)
}

get_nw_optimal_bw_cpp <- function(data, bw_grid = NULL, nsubset = NULL, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_get_nw_optimal_bw_cpp`, data, bw_grid, nsubset, kernel_name)
}

#' Local Regularity Parameters Estimation
NULL

estimate_locreg_cpp <- function(data, t, center, kernel_name = "epanechnikov", h = NULL, Delta = NULL) {
    .Call(`_adaptiveFTS_estimate_locreg_cpp`, data, t, center, kernel_name, h, Delta)
}

#' Estimate the risk of the mean function
NULL

estimate_mean_risk_cpp <- function(data, t, bw_grid = NULL, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_mean_risk_cpp`, data, t, bw_grid, kernel_name)
}

estimate_mean_cpp <- function(data, t, optbw = NULL, bw_grid = NULL, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_mean_cpp`, data, t, optbw, bw_grid, kernel_name)
}

#' Estimate the risk of the covariance or autocovariance function
NULL

estimate_autocov_risk_cpp <- function(data, s, t, lag, bw_grid = NULL, use_same_bw = FALSE, center = TRUE, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_autocov_risk_cpp`, data, s, t, lag, bw_grid, use_same_bw, center, kernel_name)
}

get_upper_tri_couple <- function(s, t) {
    .Call(`_adaptiveFTS_get_upper_tri_couple`, s, t)
}

sort_by_columns <- function(mat, first_col_idx, second_col_idx) {
    .Call(`_adaptiveFTS_sort_by_columns`, mat, first_col_idx, second_col_idx)
}

estimate_autocov_cpp <- function(data, s, t, lag, optbw_s = NULL, optbw_t = NULL, bw_grid = NULL, use_same_bw = FALSE, center = TRUE, correct_diagonal = TRUE, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_autocov_cpp`, data, s, t, lag, optbw_s, optbw_t, bw_grid, use_same_bw, center, correct_diagonal, kernel_name)
}

#' Estimate the risk of the covariance segment function
NULL

estimate_cov_segment_risk_cpp <- function(data, t, bw_grid = NULL, center = TRUE, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_cov_segment_risk_cpp`, data, t, bw_grid, center, kernel_name)
}

estimate_cov_segment_cpp <- function(data, t, optbw = NULL, bw_grid = NULL, center = TRUE, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_cov_segment_cpp`, data, t, optbw, bw_grid, center, kernel_name)
}

estimate_sigma_cpp <- function(data, t) {
    .Call(`_adaptiveFTS_estimate_sigma_cpp`, data, t)
}

estimate_empirical_mom_cpp <- function(data, t, h, mom_order, center, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_empirical_mom_cpp`, data, t, h, mom_order, center, kernel_name)
}

estimate_empirical_autocov_cpp <- function(data, t, h, lag, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_empirical_autocov_cpp`, data, t, h, lag, kernel_name)
}

estimate_empirical_XsXt_autocov_cpp <- function(data, s, t, cross_lag, lag, h, kernel_name, center) {
    .Call(`_adaptiveFTS_estimate_empirical_XsXt_autocov_cpp`, data, s, t, cross_lag, lag, h, kernel_name, center)
}

estimate_numerator_DD_single_t <- function(Znvec_raw, max_lag) {
    .Call(`_adaptiveFTS_estimate_numerator_DD_single_t`, Znvec_raw, max_lag)
}

estimate_numerator_dependence_term_DD_cpp <- function(data, t, bw_vec, h, max_lag, kernel_name, center) {
    .Call(`_adaptiveFTS_estimate_numerator_dependence_term_DD_cpp`, data, t, bw_vec, h, max_lag, kernel_name, center)
}

#' Reshape Matrix from Long Format Data
NULL

reshape_matrix <- function(A, idx_col_s, idx_col_t, idx_col_value) {
    .Call(`_adaptiveFTS_reshape_matrix`, A, idx_col_s, idx_col_t, idx_col_value)
}

combine_matrices <- function(A, B, C, D) {
    .Call(`_adaptiveFTS_combine_matrices`, A, B, C, D)
}

build_grid <- function(u, v) {
    .Call(`_adaptiveFTS_build_grid`, u, v)
}

get_best_autocov_bw <- function(mat_autocov_risk, s, t) {
    .Call(`_adaptiveFTS_get_best_autocov_bw`, mat_autocov_risk, s, t)
}

get_nearest_best_autocov_bw <- function(mat_opt_param, snew, tnew) {
    .Call(`_adaptiveFTS_get_nearest_best_autocov_bw`, mat_opt_param, snew, tnew)
}

get_best_mean_bw <- function(mat_mean_risk, t) {
    .Call(`_adaptiveFTS_get_best_mean_bw`, mat_mean_risk, t)
}

get_nearest_best_mean_bw <- function(mat_opt_param, tnew) {
    .Call(`_adaptiveFTS_get_nearest_best_mean_bw`, mat_opt_param, tnew)
}

ensure_positive_definite <- function(A, c = 1e-6) {
    .Call(`_adaptiveFTS_ensure_positive_definite`, A, c)
}

estimate_curve_cpp <- function(data, t, id_curve = NULL, bw_grid = NULL, use_same_bw = FALSE, center = TRUE, correct_diagonal = TRUE, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_curve_cpp`, data, t, id_curve, bw_grid, use_same_bw, center, correct_diagonal, kernel_name)
}

#' Mean at new locations using cached bandwidths (C++ core)
#'
#' Reuses the adaptive mean bandwidths cached in a `blup_fit` object. Called by
#' `select_tikhonov_parameter()`; not intended to be used directly.
#'
#' @param data A DataFrame with columns \code{id_curve}, \code{tobs}, \code{X}.
#' @param opt_mean Cached mean adaptive-bandwidth matrix (`t`, `optbw`).
#' @param t Evaluation locations (assumed sorted).
#' @param kernel_name Kernel name.
#' @return The mean estimates at `t`.
#' @keywords internal
blup_mean_at_cpp <- function(data, opt_mean, t, kernel_name) {
    .Call(`_adaptiveFTS_blup_mean_at_cpp`, data, opt_mean, t, kernel_name)
}

#' (Auto)covariance block at new locations using cached bandwidths (C++ core)
#'
#' Reuses the adaptive (auto)covariance bandwidths cached in a `blup_fit`
#' object. Called by `select_tikhonov_parameter()`; not intended to be used directly.
#'
#' @param data A DataFrame with columns \code{id_curve}, \code{tobs}, \code{X}.
#' @param opt_bw Cached (auto)covariance bandwidth matrix (`s`, `t`, `optbw_s`,
#'   `optbw_t`).
#' @param s,t Evaluation locations (rows indexed by `s`, columns by `t`).
#' @param lag 0 for the covariance, 1 for the lag-1 autocovariance.
#' @param correct_diagonal Whether to correct the covariance diagonal.
#' @param kernel_name Kernel name.
#' @return A `length(s)` by `length(t)` matrix of \eqn{\hat c_{lag}(s_i, t_j)}.
#' @keywords internal
blup_autocov_at_cpp <- function(data, opt_bw, s, t, lag, correct_diagonal, kernel_name) {
    .Call(`_adaptiveFTS_blup_autocov_at_cpp`, data, opt_bw, s, t, lag, correct_diagonal, kernel_name)
}

#' Fit the adaptive functional BLUP (C++ core)
#'
#' Estimates every prediction-point-independent component of the adaptive
#' Best Linear Unbiased Predictor and caches the adaptive bandwidths. Called by
#' the R function \code{blup_fit()}; not intended to be used directly.
#'
#' @param data A DataFrame with columns \code{id_curve}, \code{tobs}, \code{X}.
#' @param id_lag Integer id of the conditioning curve.
#' @param bw_grid Bandwidth grid for the adaptive risk.
#' @param rho Design weights of the conditioning curve.
#' @param homoscedastic Whether to use a constant noise variance.
#' @param tikhonov Tikhonov regularisation parameter.
#' @param sub_grid_length Number of points per axis of the bandwidth sub-grid.
#' @param kernel_name Kernel name.
#'
#' @return A list with the cached bandwidths, the covariance operator, the
#'   mean, the noise level, the regularised variance matrix and the residual.
#' @keywords internal
blup_fit_cpp <- function(data, id_lag, bw_grid, rho, homoscedastic, tikhonov, sub_grid_length, kernel_name) {
    .Call(`_adaptiveFTS_blup_fit_cpp`, data, id_lag, bw_grid, rho, homoscedastic, tikhonov, sub_grid_length, kernel_name)
}

#' Predict with the adaptive functional BLUP (C++ core)
#'
#' Evaluates the adaptive BLUP at the prediction points, looping for
#' h-step-ahead prediction. Called by \code{predict.blup_fit()}; not intended
#' to be used directly.
#'
#' @param data A DataFrame with columns \code{id_curve}, \code{tobs}, \code{X}.
#' @param opt_mean,opt_cov,opt_autocov Cached adaptive-bandwidth matrices.
#' @param Tn0 Conditioning-curve design points.
#' @param muhat_Tn0 Mean at the conditioning-curve design points.
#' @param V Regularised variance matrix of the fit.
#' @param root_D Square-root design-weight matrix of the fit.
#' @param Yn0 Conditioning-curve values (possibly overriding the fit's).
#' @param density_bw Fixed design-density bandwidth.
#' @param is_common Whether the design is common across curves.
#' @param homoscedastic Whether to use a constant noise variance.
#' @param tikhonov Tikhonov regularisation parameter.
#' @param t Prediction points.
#' @param horizon Prediction horizon (steps ahead).
#' @param kernel_name Kernel name.
#'
#' @return A matrix with columns \code{t}, \code{muhat}, \code{prediction}.
#' @keywords internal
blup_predict_cpp <- function(data, opt_mean, opt_cov, opt_autocov, Tn0, muhat_Tn0, V, root_D, Yn0, density_bw, is_common, homoscedastic, tikhonov, t, horizon, kernel_name) {
    .Call(`_adaptiveFTS_blup_predict_cpp`, data, opt_mean, opt_cov, opt_autocov, Tn0, muhat_Tn0, V, root_D, Yn0, density_bw, is_common, homoscedastic, tikhonov, t, horizon, kernel_name)
}

