# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Biweight kernel function
NULL

biweight_kernel <- function(u) {
    .Call(`_adaptiveFTS_biweight_kernel`, u)
}

triweight_kernel <- function(u) {
    .Call(`_adaptiveFTS_triweight_kernel`, u)
}

tricube_kernel <- function(u) {
    .Call(`_adaptiveFTS_tricube_kernel`, u)
}

epanechnikov_kernel <- function(u) {
    .Call(`_adaptiveFTS_epanechnikov_kernel`, u)
}

triangular_kernel <- function(u) {
    .Call(`_adaptiveFTS_triangular_kernel`, u)
}

uniform_kernel <- function(u) {
    .Call(`_adaptiveFTS_uniform_kernel`, u)
}

estimate_nw_cpp <- function(y, t, tnew, h, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_nw_cpp`, y, t, tnew, h, kernel_name)
}

estimate_nw_bw_cpp <- function(y, t, bw_grid, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_nw_bw_cpp`, y, t, bw_grid, kernel_name)
}

get_nw_optimal_bw_cpp <- function(data, bw_grid = NULL, nsubset = NULL, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_get_nw_optimal_bw_cpp`, data, bw_grid, nsubset, kernel_name)
}

#' Local Regularity Parameters Estimation
NULL

estimate_locreg_cpp <- function(data, t, center, kernel_name = "epanechnikov", h = NULL, Delta = NULL) {
    .Call(`_adaptiveFTS_estimate_locreg_cpp`, data, t, center, kernel_name, h, Delta)
}

#' Estimate the risk of the mean function
NULL

estimate_mean_risk_cpp <- function(data, t, bw_grid = NULL, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_mean_risk_cpp`, data, t, bw_grid, kernel_name)
}

estimate_mean_cpp <- function(data, t, optbw = NULL, bw_grid = NULL, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_mean_cpp`, data, t, optbw, bw_grid, kernel_name)
}

#' Estimate the risk of the covariance or autocovariance function
NULL

estimate_autocov_risk_cpp <- function(data, s, t, lag, bw_grid = NULL, use_same_bw = FALSE, center = TRUE, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_autocov_risk_cpp`, data, s, t, lag, bw_grid, use_same_bw, center, kernel_name)
}

get_upper_tri_couple <- function(s, t) {
    .Call(`_adaptiveFTS_get_upper_tri_couple`, s, t)
}

sort_by_columns <- function(mat, first_col_idx, second_col_idx) {
    .Call(`_adaptiveFTS_sort_by_columns`, mat, first_col_idx, second_col_idx)
}

estimate_autocov_cpp <- function(data, s, t, lag, optbw_s = NULL, optbw_t = NULL, bw_grid = NULL, use_same_bw = FALSE, center = TRUE, correct_diagonal = TRUE, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_autocov_cpp`, data, s, t, lag, optbw_s, optbw_t, bw_grid, use_same_bw, center, correct_diagonal, kernel_name)
}

estimate_sigma_cpp <- function(data, t) {
    .Call(`_adaptiveFTS_estimate_sigma_cpp`, data, t)
}

estimate_empirical_mom_cpp <- function(data, t, h, mom_order, center, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_empirical_mom_cpp`, data, t, h, mom_order, center, kernel_name)
}

estimate_empirical_autocov_cpp <- function(data, t, h, lag, kernel_name = "epanechnikov") {
    .Call(`_adaptiveFTS_estimate_empirical_autocov_cpp`, data, t, h, lag, kernel_name)
}

estimate_empirical_XsXt_autocov_cpp <- function(data, s, t, cross_lag, lag, h, kernel_name, center) {
    .Call(`_adaptiveFTS_estimate_empirical_XsXt_autocov_cpp`, data, s, t, cross_lag, lag, h, kernel_name, center)
}

#' Reshape Matrix from Long Format Data
NULL

reshape_matrix <- function(A, idx_col_s, idx_col_t, idx_col_value) {
    .Call(`_adaptiveFTS_reshape_matrix`, A, idx_col_s, idx_col_t, idx_col_value)
}

combine_matrices <- function(A, B, C, D) {
    .Call(`_adaptiveFTS_combine_matrices`, A, B, C, D)
}

get_best_autocov_bw <- function(mat_autocov_risk, s, t) {
    .Call(`_adaptiveFTS_get_best_autocov_bw`, mat_autocov_risk, s, t)
}

get_nearest_best_autocov_bw <- function(mat_opt_param, snew, tnew) {
    .Call(`_adaptiveFTS_get_nearest_best_autocov_bw`, mat_opt_param, snew, tnew)
}

get_best_mean_bw <- function(mat_mean_risk, t) {
    .Call(`_adaptiveFTS_get_best_mean_bw`, mat_mean_risk, t)
}

get_nearest_best_mean_bw <- function(mat_opt_param, tnew) {
    .Call(`_adaptiveFTS_get_nearest_best_mean_bw`, mat_opt_param, tnew)
}

ensure_positive_definite <- function(A, c = 1e-6) {
    .Call(`_adaptiveFTS_ensure_positive_definite`, A, c)
}

